[package]
name = "obws"
version = "0.2.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
description = "The obws (obvious) remote control library for OBS."
homepage = "https://github.com/dnaka91/obws"
repository = "https://github.com/dnaka91/obws"
categories = ["api-bindings", "web-programming"]
keywords = ["async", "obs", "obs-websocket", "remote-control", "tokio"]

[dependencies]
async-stream = "0.3.0"
base64 = "0.13.0"
bitflags = "1.2.1"
chrono = { version = "0.4.19", default-features = false, features = ["std"] }
either = { version = "1.6.1", features = ["serde"] }
futures-util = { version = "0.3.8", features = ["sink"] }
log = "0.4.11"
rgb = { version = "0.8.25", default-features = false }
semver = { version = "0.11.0", features = ["serde"] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
serde_with = "1.6.0"
sha2 = "0.9.2"
thiserror = "1.0.23"
tokio = { version = "0.3.6", features = ["net", "sync"] }
tokio-tungstenite = "0.12.0"
tungstenite = { version = "0.11.1", default-features = false }

[dev-dependencies]
anyhow = "1.0.37"
dotenv = "0.15.0"
pretty_env_logger = "0.4.0"
serde_test = "1.0.118"
tokio = { version = "0.3.6", features = ["fs", "macros", "rt-multi-thread", "time"] }

[features]
test-integration = []
